### ISSUE TITLE
essentialcarefulbreak compatibility with KleeSlabs

### ISSUE THREAD

**Issue by mrniddala** [Super-Santa/EssentialAddons#55]
Hello @Super-Santa and @blay09, I would love to have this working😊
The slabs dropping as normal item and don't getting recognized from carpet/the rule.

KleeSlabs: https://modrinth.com/mod/kleeslabs

Greetings.

**Comment by senseiwells** [comment]
While this is possible I don't want to do jank stuff to mixin to each mod that drops items not using the vanilla method. 
Supporting one mod would essentially mean that I would have to support other mods requested which I do not want to do.
I mean I could provide an API for it so that other mods can call the essential addons code, but currently I don't have the time to set that up. Maybe something for the far future.

**Comment by mrniddala** [comment]
Oki, good to know - KleeSlabs is definitely worth it ❤️
