### ISSUE TITLE
Not all blocks drop xp when mined

### ISSUE THREAD

**Issue by NoSignalBeep** [Super-Santa/EssentialAddons#77]
Hello. I have been using this mod for a while with no issues. I recently updated to 1.20.4 with 1.21 features for the crafter and trial chambers. I began mining and received no xp from mining lapis. I received it when I mined redstone and diamond ore, but then went to the nether and didn't receive xp from mining quartz or nether gold ore (I even mined several gold because they don't always drop it). Upon disabling all my mods and enabling them individually with their dependencies, I endabled Essential Addons and to my dismay, that was the culprit. Essential Client still works as intended.

**Comment by senseiwells** [comment]
I cannot reproduce, in 1.20.4 with only EssentialAddons, can you provide a list of mods & datapacks.

**Comment by NoSignalBeep** [comment]
![Screenshot 2024-02-13 202919](https://github.com/Super-Santa/EssentialAddons/assets/131561130/dce5dcc7-baa6-4e98-8563-1d1cfdab18dc)
![Screenshot 2024-02-13 203026](https://github.com/Super-Santa/EssentialAddons/assets/131561130/5b9c4a5f-74af-424d-beec-70dd3cb26057)

Thank you for your time.

**Comment by NoSignalBeep** [comment]
I'm not sure what happened, but I don't have that xp problem anymore. I should have noted I keep the same mods/datapacks in every world. Thank you if you did fix it! I love this mod so much. Careful break saves a lot of headache when working around hoppers and such. I appreciate your time.

**Comment by NoSignalBeep** [comment]
I apologize. I figured it out. It's when I subscribe to careful break that the xp doesn't drop. When I unsubscribe to that, xp drops.

**Comment by senseiwells** [comment]
Since your list of mods/datapacks is so extensive I do not have the time to download each one let alone test all of them or read their code.
I have reworked how carefulbreak is implemented - if you are still having this issue then I suggest you remove your mods until you find which one is at fault and report it to them since this implementation should be compatible with everything - it would be on their end.
You can download the updated version [here](https://filebin.net/5fu6x6lyn9ib86sl/EssentialAddons-1.20.4-1.3.4.jar).
Please let me know if this doesn't fix your issue.
